In [1]:
import tensorflow as tf
from simple_model import TranslationModel
from utils import castom_layers
from utils.text_vectorise import custom_standardize
from keras.models import load_model

2025-08-07 16:51:57.096022: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-08-07 16:51:57.347846: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-08-07 16:51:57.452485: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8473] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-08-07 16:51:57.486181: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1471] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-08-07 16:51:57.658873: I tensorflow/core/platform/cpu_feature_guar

In [4]:
model: TranslationModel = load_model('models/translation_model_final.keras',
                                    custom_objects={
                                        'DecoderMask': castom_layers.DecoderMask,
                                        'PadMask': castom_layers.PadMask,
                                        'PositionalEncoding': castom_layers.PositionalEncoding,
                                        'custom_standardize': custom_standardize,
                                        'TranslationModel': TranslationModel
                                    }
                                )

/usr/local/lib/python3.12/dist-packages/keras/src/layers/layer.py:360: UserWarning: `build()` was called on layer 'positional_encoding_2', however the layer does not have a `build()` method implemented and it looks like it has unbuilt state. This will cause the layer to be marked as built, despite not being actually built, which may cause failures down the line. Make sure to implement a proper `build()` method.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/keras/src/layers/layer.py:360: UserWarning: `build()` was called on layer 'positional_encoding_3', however the layer does not have a `build()` method implemented and it looks like it has unbuilt state. This will cause the layer to be marked as built, despite not being actually built, which may cause failures down the line. Make sure to implement a proper `build()` method.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/keras/src/saving/serialization_lib.py:730: UserWarning: Model 'translation_model_1' had a build 

In [5]:
model.summary()

Model: "encoder_model"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_phrase        │ (None, 800)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embeding            │ (None, 800, 256)  │     19,712 │ input_phrase[0][… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ positional_encodin… │ (None, 800, 256)  │    204,800 │ embeding[0][0]    │
│ (PositionalEncodin… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ pad_mask_2          │ (None, 1, 1, 800) │          0 │ input_phrase[0][… │
│ (PadMask)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 800, 256)  │  2,103,552 │ positional_encod… │
│ (MultiHeadAttentio… │                   │            │ positional_encod… │
│                     │                   │            │ positional_encod… │
│                     │                   │            │ pad_mask_2[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add (Add)           │ (None, 800, 256)  │          0 │ multi_head_atten… │
│                     │                   │            │ positional_encod… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalization │ (None, 800, 256)  │        512 │ add[0][0]         │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 800, 256)  │     65,792 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_1 (Add)         │ (None, 800, 256)  │          0 │ layer_normalizat… │
│                     │                   │            │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 800, 256)  │        512 │ add_1[0][0]       │
│ (LayerNormalizatio… │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 2,394,880 (9.14 MB)

 Trainable params: 2,394,880 (9.14 MB)

 Non-trainable params: 0 (0.00 B)

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ decoder_input       │ (None, 800)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ emb_decoder         │ (None, 800, 256)  │     19,712 │ decoder_input[0]… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ positional_encodin… │ (None, 800, 256)  │    204,800 │ emb_decoder[0][0] │
│ (PositionalEncodin… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ decoder_mask_1      │ (None, 1, 800,    │          0 │ decoder_input[0]… │
│ (DecoderMask)       │ 800)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 800, 256)  │  2,103,552 │ positional_encod… │
│ (MultiHeadAttentio… │                   │            │ positional_encod… │
│                     │                   │            │ positional_encod… │
│                     │                   │            │ decoder_mask_1[0… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_2 (Add)         │ (None, 800, 256)  │          0 │ multi_head_atten… │
│                     │                   │            │ positional_encod… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 800, 256)  │        512 │ add_2[0][0]       │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embeding            │ (None, 800, 256)  │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 800, 256)  │  2,103,552 │ layer_normalizat… │
│ (MultiHeadAttentio… │                   │            │ embeding[0][0],   │
│                     │                   │            │ embeding[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_3 (Add)         │ (None, 800, 256)  │          0 │ layer_normalizat… │
│                     │                   │            │ multi_head_atten… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 800, 256)  │        512 │ add_3[0][0]       │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 800, 256)  │     65,792 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_4 (Add)         │ (None, 800, 256)  │          0 │ layer_normalizat… │
│                     │                   │            │ dense_2[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 800, 256)  │        512 │ add_4[0][0]       │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 800, 128)  │     32,896 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 800, 77)   │      9,933 │ dense_3[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 4,541,773 (17.33 MB)

 Trainable params: 4,541,773 (17.33 MB)

 Non-trainable params: 0 (0.00 B)

In [6]:
input_data = tf.constant(['Hello'], dtype=tf.string)
# input_data = tf.constant(['Olá', 'o meu nome é', 'onde'], dtype=tf.string)

In [19]:
input_vectorized = model.text_vector(input_data)

# Створюємо <START> токени для декодера
batch_size = tf.shape(input_vectorized)[0]
decoder_input = tf.tile(model.text_vector(['<START>']), [batch_size, 1])

result_tokens = []

vocab = model.text_vector.get_vocabulary()

for i in range(1, 800):
    output_logits = model(input_vectorized, decoder_input, training=False)
    next_token = tf.argmax(output_logits[:, i], axis=-1)
    decoder_input = tf.tensor_scatter_nd_update(decoder_input, [[k, i] for k, _ in enumerate(range(batch_size))], next_token)
    # token_ids = decoder_input.numpy()
    # decoded_texts = []
    # for row in tf.argmax(output_logits, axis=-1).numpy():
    #     chars = [vocab[i] for i in row]
    #     decoded_texts.append("".join(chars))
    #     print(decoded_texts)

    if tf.reduce_all(tf.equal(next_token, model.text_vector('<END>')[0])):
        break
        
decoded_texts = []
for row in decoder_input:
    chars = [vocab[i] for i in row]
    decoded_texts.append("".join(chars))
    print(decoded_texts)

['[UNK][UNK]e[UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK]ee[UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK]e[UNK]ee[UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK]e[UNK][UNK][UNK][UNK][UNK]e[UNK][UNK][UNK][UNK][UNK]eeeee[UNK][UNK][UNK]eeee[UNK]ee[UNK]eeeeeeeeeeeeee[UNK]eeeee[UNK][UNK][UNK][UNK][UNK][UNK]e[UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK]e[UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK][UNK]ee[UNK][UNK][UNK][UNK]e[UNK][UNK][UNK][UNK]eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee[UNK]eeeeeee[UNK]eeeeeeeee[UNK]eeeeeeeeee[UNK]eeeeeeeeeeeeee[UNK]e[UNK]eeeeeee[UNK]eeeeeeeee[UNK]ee[UNK]eee[UNK]e[UNK]ee[UNK]e[UNK]eeeeee[UNK]eee

In [21]:
decoder_input, decoded_texts

(<tf.Tensor: shape=(1, 800), dtype=int64, numpy=
 array([[45,  1, 52, 44, 52, 63, 65, 52, 52, 44, 52, 44, 62, 67, 60, 44,
         62, 51, 44, 62, 54, 62, 67, 44, 52, 65, 62, 62, 44, 52, 63, 67,
         44, 52, 65, 62, 63, 56, 62, 62,  1, 66, 65, 62, 52, 62,  1, 66,
         65, 62, 52, 44, 66, 48, 44, 68, 63, 66, 48, 44, 62, 67, 60, 68,
         48, 44, 62, 67, 65, 68, 56, 65, 44, 62, 67, 62, 62, 44, 52, 66,
         68, 44, 62, 67, 60, 68, 48, 44, 62, 67, 65, 52, 44, 52, 63, 65,
         52, 52, 44, 68, 66, 48, 44, 62, 67, 61, 56, 68, 56, 44, 62, 67,
         65, 52, 44, 52, 63, 65, 52, 56, 44, 66, 62, 66, 44, 62, 61, 66,
         56, 62, 52, 44, 65, 48, 56, 44, 66, 48, 44,  1, 52, 44, 44, 62,
         66, 61, 54, 52, 67, 67, 44, 52, 44, 66, 59, 67, 65, 52, 44, 52,
         44, 52, 44, 68, 63, 66, 48, 44, 65, 52, 44, 52, 44, 52, 63, 48,
         56, 44, 60, 59,  1, 56, 62, 62, 44, 62, 66, 62, 65, 52, 44, 52,
         44, 52, 63, 52, 48, 44, 52, 63, 52, 48, 56, 44, 62, 67, 44, 62,
  

In [5]:
from keras import ops

In [6]:
pad_mask = castom_layers.PadMask()

In [5]:
pad_mask(tf.constant([[1, 2, 3, 4, 0]]))

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1., 1., 1., 1., 0.]]]], dtype=float32)>

In [6]:
dec_mask = castom_layers.DecoderMask()

In [7]:
dec_mask(tf.constant([[1, 2, 3, 4, 0]]))

<tf.Tensor: shape=(1, 5, 5), dtype=int32, numpy=
array([[[1, 0, 0, 0, 0],
        [1, 1, 0, 0, 0],
        [1, 1, 1, 0, 0],
        [1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1]]], dtype=int32)>

In [21]:
pad_mask = castom_layers.PadMask()

In [7]:
input_data = tf.constant([[1, 2, 3, 4, 0]])
input_shape = ops.shape(input_data)
batch_size, sequence_length = input_shape[0], input_shape[1]
i = ops.arange(sequence_length)[:, None]
j = ops.arange(sequence_length)
mask = ops.cast(i >= j, dtype="int32")  # type: ignore
mask = ops.reshape(mask, (1, sequence_length, sequence_length))
mult = ops.concatenate(
    [ops.expand_dims(batch_size, -1), ops.convert_to_tensor([1, 1])],
    axis=0,
)
mask = ops.tile(mask, mult)
mask = tf.expand_dims(mask, axis=1)
pad_m = pad_mask(input_data)
pad_m = tf.reshape(pad_m, input_shape)

mask, pad_m

(<tf.Tensor: shape=(1, 1, 5, 5), dtype=int32, numpy=
 array([[[[1, 0, 0, 0, 0],
          [1, 1, 0, 0, 0],
          [1, 1, 1, 0, 0],
          [1, 1, 1, 1, 0],
          [1, 1, 1, 1, 1]]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 5), dtype=float32, numpy=array([[1., 1., 1., 1., 0.]], dtype=float32)>)